<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Combat Export</title>
    <style>
        /* Minimal print-only styles */
        @media print {
            @page {
                size: landscape;
                margin: 5mm;
            }

            body {
                font-family: Arial, sans-serif;
                font-size: 9pt;
                margin: 0;
                padding: 0;
                color: #000;
                background: #fff;
            }

            /* Hide everything except the export content */
            .no-print {
                display: none !important;
            }

            .print-container {
                width: 100%;
                padding: 0;
                margin: 0;
            }

            .print-header {
                text-align: center;
                margin-bottom: 5mm;
                padding-bottom: 2mm;
                border-bottom: 1px solid #00162E;
            }

            .print-title {
                font-size: 14pt;
                color: #00162E;
                margin: 0 0 2mm 0;
            }

            .print-date {
                font-size: 9pt;
                color: #666;
            }

            .combat-table {
                width: 100%;
                border-collapse: collapse;
                font-size: 8pt;
                page-break-inside: auto;
            }

            .combat-table th {
                background: #00162E;
                color: white;
                padding: 1.5mm;
                text-align: left;
                font-weight: bold;
                border: 1px solid #00162E;
            }

            .combat-table td {
                padding: 1.5mm;
                border: 1px solid #ddd;
                text-align: left;
            }

            .combat-table tr:nth-child(even) {
                background: #f8f8f8;
            }

            /* REMOVE FIXED POSITIONING */
            .print-footer {
                text-align: center;
                font-size: 7pt;
                color: #666;
                padding: 1mm 0;
            }
        }
    </style>
</head>

<body>
    <!-- Print button visible only in browser -->
    <div class="no-print" style="text-align: center; padding: 20px;">
        <button onclick="window.print()"
            style="
            background: #AE8708;
            color: #000917;
            border: none;
            padding: 10px 20px;
            font-size: 16px;
            border-radius: 4px;
            cursor: pointer;
            margin: 20px;
        ">
            Print Export
        </button>
        <p>This document is ready for printing. Click the button above or use your browser's print function.</p>
    </div>

    <div class="print-container">
        <div class="print-header">
            <h1 class="print-title">Pathfinder 2e Combat Export</h1>
            <div class="print-date">Generated: {{ now()->format('d-m-Y, H:i') }}</div>
        </div>

        <table class="combat-table">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Type</th>
                    <th>AC</th>
                    <th>HP</th>
                    <th>Fortitude</th>
                    <th>Reflex</th>
                    <th>Will</th>
                    <th>Initiative</th>
                    <th>Perception</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($combatants as $combatant)
                    <tr>
                        <td>{{ $combatant['name'] }}</td>
                        <td>{{ $combatant['type'] }}</td>
                        <td>{{ $combatant['ac'] }}</td>
                        <td>{{ $combatant['currentHp'] }}/{{ $combatant['maxHp'] }}</td>
                        <td>{{ $combatant['fortSave'] ?? ($combatant['fortitude'] ?? '-') }}</td>
                        <td>{{ $combatant['refSave'] ?? ($combatant['reflex'] ?? '-') }}</td>
                        <td>{{ $combatant['willSave'] ?? ($combatant['will'] ?? '-') }}</td>
                        <td>{{ $combatant['initiative'] }}</td>
                        <td>{{ $combatant['perception'] }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        <div class="print-footer">
            Generated by Pathfinder 2e Combat Manager | {{ config('app.url') }}
        </div>
    </div>
</body>

</html>
